// <auto-generated />
using System;
using JCTMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JCTMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("JCTMS.Core.Entities.Case", b =>
                {
                    b.Property<int>("CaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourtRoom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JudgeID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CaseID");

                    b.HasIndex("JudgeID");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Hearing", b =>
                {
                    b.Property<int>("HearingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HearingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.HasKey("HearingID");

                    b.HasIndex("CaseID");

                    b.ToTable("Hearings");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Judge", b =>
                {
                    b.Property<int>("JudgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("JudgeID");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Party", b =>
                {
                    b.Property<int>("PartyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartyID");

                    b.HasIndex("CaseID");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Sequence", b =>
                {
                    b.Property<string>("SequenceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("SequenceName");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Case", b =>
                {
                    b.HasOne("JCTMS.Core.Entities.Judge", "Judge")
                        .WithMany("AssignedCases")
                        .HasForeignKey("JudgeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Judge");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Hearing", b =>
                {
                    b.HasOne("JCTMS.Core.Entities.Case", "Case")
                        .WithMany("Hearings")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Party", b =>
                {
                    b.HasOne("JCTMS.Core.Entities.Case", "Case")
                        .WithMany("Parties")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Case", b =>
                {
                    b.Navigation("Hearings");

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("JCTMS.Core.Entities.Judge", b =>
                {
                    b.Navigation("AssignedCases");
                });
#pragma warning restore 612, 618
        }
    }
}
